//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int codigo { get; set; }
        public string nome { get; set; }
        public Nullable<int> idade { get; set; }
    }
}
